### ISSUE TITLE
Clarify documentation on Event graph

### ISSUE THREAD

**Issue by sebastienfi** [Squad-Wiki-Editorial/squad-wiki-pipeline-map-data#18]
Is that what the Event Graph should look like?
Duration of delay is 5.0 ?

![image](https://user-images.githubusercontent.com/5808108/164955110-814b10dc-814a-41ff-b2d8-f3f242d7f4e0.png)

**Comment by Shanomac99** [comment]
This is correct, but I haven't updated this BP on the GitHub in a long time. I will be depreciating this project in a few weeks for a different project that works better then this.
