### ISSUE TITLE
Missing data from a couple layers in recent finished_4.0.json

### ISSUE THREAD

**Issue by LukeeSucks** [Squad-Wiki-Editorial/squad-wiki-pipeline-map-data#42]
Manic Invasion v2 (Line ~79043) "faction", "teamSetupName", "tickets" and "playerPercent" is missing from "team2".
Sumari Bala Seed v2 (Line ~102350) "tickets" "teamSetupName" "playerPercent" and "disabledVeh" is missing from "team2".

**Comment by werewolfboy13** [comment]
> Manic Invasion v2 (Line ~79043) "faction", "teamSetupName", "tickets" and "playerPercent" is missing from "team2".

Is missing from raw text, will rerun and validate. 

> Sumari Bala Seed v2 (Line ~102350) "tickets" "teamSetupName" "playerPercent" and "disabledVeh" is missing from "team2".

Same as above, will validate.
