### ISSUE TITLE
Failed to compile mapgrabasset

### ISSUE THREAD

**Issue by M3dinar** [Squad-Wiki-Editorial/squad-wiki-pipeline-map-data#5]
I tried to export French faction information to JSON but the mapGrabAsset BP does not compile.
I can see it was not update with the layer overhaul.
![image](https://user-images.githubusercontent.com/36376550/119534143-e169b280-bd86-11eb-9c77-469f15ce892a.png)

**Comment by Shanomac99** [comment]
e97aaa7 Should fix this. 

Please note that the blueprint I uploaded extracts more data now, including Capture points, spawners, and assets.

I'd also recommend temporarily removing the vanilla directory in the BP_SQLevel_C primary asset from the Asset Manager. Not removing this _may_ cause the vanilla layers to run. The extractor shouldn't run vanilla maps if you load into a modded map first but I have noticed weird issues when testing out CAF.

**Comment by M3dinar** [comment]
Yeah it fix the compile error but i got other problem after which i fixed 
-Added role faction mod
-Added vehicle faction mod

But I didn't fix this one:
-Changemap does not work after the first one. The 2 loops on SQ_Layer seems to be wrong, Index for changemap is always 2.

I will take a look another time.
