### ISSUE TITLE
No more update ?

### ISSUE THREAD

**Issue by remrem** [Squad-Wiki-Editorial/squad-wiki-pipeline-map-data#9]
Hi!

I use the datas provided by [completed_output](https://github.com/Squad-Wiki-Editorial/squad-wiki-pipeline-map-data/blob/master/completed_output/_Current%20Version/finished.json) for some scripts and, guys, thanks for this, save me a lot of time !

But there is no update since last month, and nothing about anvil. So, are you planning an update ?

Take care.

**Comment by Shanomac99** [comment]
Hi there! I'll update it sometime tonight, totally forgot to upload it to github, my apologies.

**Comment by remrem** [comment]
no worries, Thanks!
